### ISSUE TITLE
hi! Does anyone know what‘s the rest of input param of compile.bat?

### ISSUE THREAD

**Issue by wqlxx** [Keenuts/virtio-gpu-win-icd#1]
I find in compile.bat, the first param is "mode", but what's the others?

**Comment by Keenuts** [comment]
Hi !

First one are indeed ICD or DEMO
The second one, form the top of my head is Release or Debug, and the third one
if the target architecture
An example should be  ./compile.bat ICD Debug Win32

The values can be fetched inside the corresponding .vcxproj

**Comment by qiang-w-ruijie** [comment]
Thanks  @Keenuts
