### ISSUE TITLE
How to use this file ?

### ISSUE THREAD

**Issue by ranggatry** [Keenuts/virtio-gpu-win-icd#2]
Hi. Does anyone know how to use this file ? i have trying with double click with administrator privileges and then with change directory into the file path with command prompt then i run compile.bat . But it seems it's not the right way.

**Comment by Keenuts** [comment]
Hi Ranggatry,

**Please, see the issue #1 .**
Please, at least take a rapid look at the previous posted issues. There is only 1 other issue on the list, and it contains what you want.

Please, also note this **IS NOT a production ready project**. It's a toy OpenGL ICD designed to work on 1 specific fork of the virtiogpu windows kernel driver, on QEMU/KVM only, with all the stars properly aligned. **It works ONLY in ONE specific environment**, and **SHOULD NOT be used**.
