### ISSUE TITLE
please archive/delete this project

### ISSUE THREAD

**Issue by ghost** [Keenuts/virtio-gpu-win-icd#3]
and inform anybody with references to it's support or development to stop indicating that it works or will ever be a thing. thanks.

**Comment by kotatsuyaki** [comment]
The readme of this repo literally says “this project is not supposed to compile” and the current state of the project, so I don’t see any problem.

**Comment by mirh** [comment]
"In progress" is kinda misleading to be fair. 
On the other hand.. I guess the major problem is that you need a kernel driver to be able to run this in the first place?
https://lists.freedesktop.org/archives/spice-devel/2019-March/048643.html
https://gitlab.freedesktop.org/spice/win32/virtio-gpu-wddm-dod
https://bugzilla.redhat.com/show_bug.cgi?id=1861229
https://github.com/virtio-win/kvm-guest-drivers-windows/tree/master/viogpu
And that's slowly coming along I guess.

**Comment by Keenuts** [comment]
Hi all!

Thanks for your interest in this project! I agree the "In progress" part is misleading! Just removed it from the README as I don't work on this project anymore (day job, life, blabla).

About the project status:
- I don't work on this project anymore.
- I receive regular inquiries about companies trying to work on this project. I don't have more info that "some are trying".
- The source of truth can be found on the virglrenderer-devel mailing list. Last update is from January 2021:
https://lists.freedesktop.org/archives/virglrenderer-devel/2021-January/001896.html
